### ISSUE TITLE
Push7BOXへの対応

### ISSUE THREAD

**Issue by yoichiro-mikami** [gnexltd/push7-wp-plugin#17]
現在開発中のPush7BOXについて、チェックボックス1つで導入ができるように対応を行う。

**Comment by shumbo** [comment]
リリースされたので実装したいですが、当時と大幅に機能が異なるので再検討する必要がありそうです。

具体的には、BOXを表示するかどうかはダッシュボードで決定される事項なので表示/非表示のオプションは必要なく、代わりにSDKのオプションを設定できるようにするべきだと思います。

SDKのオプションは

+ mode: NormalモードとNativeモード
+ subscribe: Nativeモードにおける購読するタイミング

の2つがあります。
