### ISSUE TITLE
subversionが古いため自動デプロイが動作しない

### ISSUE THREAD

**Issue by otofune** [gnexltd/push7-wp-plugin#44]
### 詳細
Travis CIのデフォルトディストリビューションであるUbuntu 12.04に搭載されたsubversionは1.6.17で、フォルダごとに `.svn` (管理用ディレクトリ) を保持する構造のsubversionなのだが、`.deploy.sh`ではWC-NG (Working Copy Next Generation) という `.svn` がルートにしかない機能を前提としており、この機能はsubversion 1.7以降でないと対応しておらず、そのためデプロイ処理が手元では動作し、Travis CI上で動作しない

### 回避策
- [ ] CI環境としてtrustyを使う (subversion 1.8.8)  
PHP 5.3が使えなくなる問題点はあるが動作確認済み
- [ ] デフォルトのUbuntu 12.04 (subversion 1.6.17) にaptリポジトリを追加しsubversionを1.8以降にする
- [ ] 1.7以前の.svnフォルダが個別にある状況に対応した.deploy.shにする

僕としては、最低バージョンを引き上げられたらいいなと思っています。https://github.com/gnexltd/push7-wp-plugin/pull/43 による集計を期待したいです。

**Comment by potato4d** [comment]
@otofune 
これ、ちょっと思ったんだけど、CIをMatrix環境にして、特定のENV以外では動作しないようにする判定仕込めばいけないかな？

**Comment by otofune** [comment]
イケそう

**Comment by potato4d** [comment]
@otofune 
 otofune was assigned by potato4d just now

**Comment by potato4d** [comment]
一旦Mergeしたので次のリリースで動作が確認できたらClose。

**Comment by otofune** [comment]
動作したのでclose
